name: JH-RBIF120-project
channels:
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - wget
  - samtools=1.22
  - bedtools=2.31
  - numpy=2.1
  - pandas
  - biopython=1.86
  - plotly=6.0
  - matplotlib=3.10
  - cuda-toolkit=12.5
  - cudnn=9.3
  - pip:
      - tensorflow==2.19.*
      - keras-tcn==3.5.6
      - npy-append-array==0.9.19