name: JH-RBIF120-project
channels:
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - jupyterlab
  - pip
  - wget # TODO: decide between wget or curl and update data retrieval scripts
  - curl # TODO: decide between wget or curl and update data retrieval scripts
  - bash
  - gzip
  - unzip
  - samtools=1.22
  - bedtools=2.31
  - numpy=2.1
  - pandas
  - biopython=1.86
  - plotly=6.0
  - matplotlib=3.10
  - pip:
      - --find-links https://repo.radeon.com/rocm/manylinux/rocm-rel-7.1/ # NOTE: version # in this line may need adapting based on the age of your hardware (UNTESTED, see README)
      - tensorflow-rocm==2.19.* # NOTE: version # in this line may need adapting based the line above and the age of your hardware (UNTESTED, see README)
      - keras-tcn==3.5.6
      - npy-append-array==0.9.19